name: Build

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  XMAKE_GLOBALDIR: ${{ github.workspace }}/.xmake-global
  XMAKE_PKG_CACHEDIR: ${{ github.workspace }}/.xmake-cache

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Hash deps
        id: hashes
        run: |
          $depsHash = (Get-FileHash -Algorithm SHA256 -Path xmake.lua).Hash.Substring(0, 16)
          echo "deps=$depsHash" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: Cache xmake packages
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.XMAKE_GLOBALDIR }}
            ${{ env.XMAKE_PKG_CACHEDIR }}
            ${{ env.LOCALAPPDATA }}\.xmake
          key: pkgs-${{ steps.hashes.outputs.deps }}
          restore-keys: |
            pkgs-
          save-always: true

      - name: Build
        run: |
          xmake f -a x64 -m release -p windows -y
          xmake -y -j $env:NUMBER_OF_PROCESSORS
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.run_number }}
          path: bin/
